// src/chi-vue/src/components/expansion-panel/ExpansionPanel.tsx
import { Prop, Watch } from 'vue-property-decorator';
import { EXPANSION_PANEL_STATES, ExpansionPanelState } from '@/constants/types';
import { EPANEL_CLASSES, UTILITY_CLASSES } from '@/constants/classes';
import './expansion-panel.scss';
import { EPANEL } from '@/constants/constants';
import { Component, Vue } from '@/build/vue-wrapper';
import Tooltip from '@/components/tooltip/tooltip';
import { Transition } from 'vue';

@Component({})
export default class ExpansionPanel extends Vue {
  @Prop({ default: 'pending' }) state!: ExpansionPanelState;
  @Prop() title!: string;
  @Prop() step!: string;
  @Prop() bordered?: boolean;
  @Prop() stateIcon?: boolean;
  @Prop({ default: EPANEL.DEFAULT_TOOLTIP_CONTENT }) stateIconTooltip?: string;

  @Watch('state')
  stateValidation(newValue: ExpansionPanelState) {
    if (newValue && !EXPANSION_PANEL_STATES.includes(newValue)) {
      throw new Error(
        `${newValue} is not a valid state of Expansion Panel. If provided, valid values are ${EXPANSION_PANEL_STATES.join(
          ', '
        )}`
      );
    }
  }

  render() {
    const slots = {
      active: this.$slots.active ? this.$slots.active({}) : null,
      change: this.$slots.change ? this.$slots.change({}) : null,
      done: this.$slots.done ? this.$slots.done({}) : null,
      footer: this.$slots.footer ? this.$slots.footer({}) : null,
      footerStart: this.$slots['footer-start'] ? this.$slots['footer-start']({}) : null,
      footerEnd: this.$slots['footer-end'] ? this.$slots['footer-end']({}) : null,
    };
    const footerStartEnd =
      slots.footerStart || slots.footerEnd ? (
        <div
          class={`${UTILITY_CLASSES.SIZING.W100} ${UTILITY_CLASSES.DISPLAY.FLEX} ${UTILITY_CLASSES.JUSTIFY.CONTENT_BETWEEN}`}>
          <div>{slots.footerStart}</div>
          <div>{slots.footerEnd}</div>
        </div>
      ) : null;

    return (
      <div
        class={`${EPANEL_CLASSES.EPANEL} ${this.state ? `-${this.state}` : ''}
      ${this.bordered ? EPANEL_CLASSES.BORDERED : ''} ${this.stateIcon ? EPANEL_CLASSES.STATE_ICON : ''}`}>
        <div class={EPANEL_CLASSES.HEADER}>
          {this.stateIcon && (
            <Tooltip message={this.stateIconTooltip}>
              <chi-icon icon="circle-check" size="sm--2" color="success" class={EPANEL_CLASSES.STATE}></chi-icon>
            </Tooltip>
          )}
          {this.step ? <span class={EPANEL_CLASSES.NUMBER}>{this.step}.</span> : ''}
          <div class={EPANEL_CLASSES.TITLE}>{this.title}</div>
          <div class={`${EPANEL_CLASSES.CONTENT} ${this.step ? '' : UTILITY_CLASSES.MARGIN.LEFT[0]}`}>
            <Transition name={EPANEL.TRANSITIONS.SLIDE_FADE}>
              <div v-show={this.state === 'done'} class={EPANEL_CLASSES.DONE_ONLY}>
                {slots.done}
              </div>
            </Transition>
          </div>
          <Transition name={EPANEL.TRANSITIONS.SLIDE_FADE}>
            <div v-show={this.state === 'done'} class={EPANEL_CLASSES.ACTION}>
              {slots.change}
            </div>
          </Transition>
        </div>
        <Transition name={EPANEL.TRANSITIONS.SLIDE_FADE}>
          <div v-show={this.state === 'active'}>
            <div class={`${this.step ? '' : UTILITY_CLASSES.MARGIN.LEFT[0]} ${EPANEL_CLASSES.CONTENT_ACTIVE}`}>
              <div class={EPANEL_CLASSES.BODY}>
                <div class={EPANEL_CLASSES.CONTENT}>{slots.active}</div>
                <div class={`${EPANEL_CLASSES.FOOTER} ${UTILITY_CLASSES.JUSTIFY.END}`}>
                  {slots.footer}
                  {footerStartEnd}
                </div>
              </div>
            </div>
          </div>
        </Transition>
      </div>
    );
  }
}

// src/custom-elements/src/components/expansion-panel/expansion-panel.tsx
import { Component, Prop, Watch, h, Element, State } from '@stencil/core';
import { EPANEL_CLASSES, GENERIC_SIZE_CLASSES, ICON_CLASS, ICONS, UTILITY_CLASSES } from '../../constants/classes';
import { EPANEL_TOOLTIP_CONTENT } from '../../constants/constants';
import { addMutationObserver } from '../../utils/mutationObserver';

const EP_MODES = ['done', 'active', 'pending', 'disabled'];

declare const chi: any;

@Component({
  tag: 'chi-expansion-panel',
  styleUrl: 'expansion-panel.scss',
  scoped: true,
})
export class ExpansionPanel {
  @Element() el;
  /**
   * to set expansion panel state. Possible values are: {'done', 'active', 'pending' (default value), and 'disabled'}
   */
  @Prop({ reflect: true }) state = 'pending';

  /**
   * to set a step number next to the title of the panel
   */
  @Prop({ reflect: true }) step: string;

  /**
   * to set the panel style to bordered
   */
  @Prop({ reflect: true }) bordered: boolean;

  /**
   * to set the title of the panel
   */
  @Prop({ attribute: 'title', reflect: true }) epanelTitle: string;

  /**
   * to render a state icon within the panel
   */
  @Prop({ reflect: true }) stateIcon = false;

  /**
   * to render a state tooltip
   */
  @Prop({ reflect: true }) stateIconTooltip = EPANEL_TOOLTIP_CONTENT;

  private tooltip: any;

  @Watch('state')
  stateValidation(newValue: string) {
    if (newValue && !EP_MODES.includes(newValue)) {
      throw new Error(
        `${newValue} is not a valid state for this component. If provided, valid values are 'done', 'active', 'pending' or 'disabled'; if not, 'pending' value will be set. `
      );
    }
  }

  connectedCallback() {
    addMutationObserver.call(this);
  }

  componentWillLoad() {
    this.stateValidation(this.state);
  }

  componentDidLoad() {
    this.tooltip = chi.tooltip(document.getElementById('state-icon-tooltip'));
  }

  disconnectedCallback() {
    if (this.tooltip) {
      this.tooltip.dispose();
      this.tooltip = null;
    }
  }

  render() {
    return (
      <div
        class={`${EPANEL_CLASSES.EPANEL} 
        ${this.state === 'disabled' ? `-disabled` : ''}
        ${this.state === 'active' ? `-active` : ''}
        ${this.state === 'done' ? `-done` : ''}
        ${this.bordered ? EPANEL_CLASSES.BORDERED : ''}
        ${this.stateIcon ? EPANEL_CLASSES.STATE_ICON : ''}
        ${this.step ? '' : '-no-step'}`}
      >
        <div class={EPANEL_CLASSES.HEADER}>
          {this.stateIcon && (
            <i
              class={`${ICON_CLASS} ${ICONS.SUCCESS} icon-circle-check ${GENERIC_SIZE_CLASSES.SM_2} ${EPANEL_CLASSES.STATE}`}
              id="state-icon-tooltip"
              data-tooltip={this.stateIconTooltip}
            />
          )}
          {this.step ? <span class={EPANEL_CLASSES.NUMBER}>{this.step}.</span> : ''}
          <div class={EPANEL_CLASSES.TITLE}>{this.epanelTitle}</div>
          <div class={EPANEL_CLASSES.CONTENT}>
            <div class={EPANEL_CLASSES.COLLAPSE}>
              <div class={EPANEL_CLASSES.DONE_ONLY}>
                <slot name="done" />
              </div>
            </div>
          </div>
          {this.state === 'done' || this.state === 'active' ? (
            <div class={EPANEL_CLASSES.ACTION}>
              <slot name="change" />
            </div>
          ) : (
            ''
          )}
        </div>
        <div class={EPANEL_CLASSES.COLLAPSE}>
          <div class={EPANEL_CLASSES.ACTIVE_ONLY}>
            <div class={EPANEL_CLASSES.BODY}>
              <div class={EPANEL_CLASSES.CONTENT}>
                <slot name="active" />
              </div>
              <div class={`${EPANEL_CLASSES.FOOTER} ${UTILITY_CLASSES.JUSTIFY.END}`}>
                <slot name="footer" />
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
