// src/boilerplates/vue/vue-boilerplate/src/App.vue
<template>
  <div id="app">
    <div class="hello -h--100">
      <Header />
      <div
        class="-d--flex -w--100 -h--100 -align-items--center -justify-content--center"
      >
        <button
          id="modal-trigger-1"
          class="chi-button chi-modal__trigger"
          data-target="#modal-1"
        >
          Launch demo modal
        </button>

        <div class="chi-backdrop -closed">
          <div class="chi-backdrop__wrapper">
            <section
              id="modal-1"
              class="chi-modal"
              role="dialog"
              aria-label="Modal description"
              aria-modal="true"
            >
              <header class="chi-modal__header">
                <h2 class="chi-modal__title">Modal Title</h2>
                <button
                  class="chi-button -icon -close"
                  data-dismiss="modal"
                  aria-label="Close"
                >
                  <div class="chi-button__content">
                    <i class="chi-icon icon-x"></i>
                  </div>
                </button>
              </header>
              <div class="chi-modal__content">
                <p class="-text -m--0">Modal content</p>
              </div>
              <footer class="chi-modal__footer">
                <button class="chi-button" data-dismiss="modal">Cancel</button>
                <button class="chi-button -primary">Save</button>
              </footer>
            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import Header from './components/Header.vue';

declare const chi: any;
@Component({
  components: {
    Header
  }
})
export default class App extends Vue {
  mounted() {
    chi.modal(document.getElementById('modal-trigger-1'));
  }
}
</script>

<style lang="scss">
html,
body,
#app {
  width: 100%;
  height: 100%;
}
</style>

// src/boilerplates/react/chi-react-boilerplate/src/App.tsx
import React from 'react';
import './App.css';
import Header from './components/header';

declare const chi: any;

class App extends React.Component {
  componentDidMount() {
    chi.modal(document.getElementById('modal-trigger-1'));
  }

  render() {
    return (
      <div className="hello -h--100">
        <Header />
        <div
          className="-d--flex -w--100 -h--100 -align-items--center -justify-content--center"
        >
          <button
            id="modal-trigger-1"
            className="chi-button chi-modal__trigger"
            data-target="#modal-1"
          >
            Launch demo modal
            </button>

          <div className="chi-backdrop -closed">
            <div className="chi-backdrop__wrapper">
              <section
                id="modal-1"
                className="chi-modal"
                role="dialog"
                aria-label="Modal description"
                aria-modal="true"
              >
                <header className="chi-modal__header">
                  <h2 className="chi-modal__title">Modal Title</h2>
                  <button
                    className="chi-button -icon -close"
                    data-dismiss="modal"
                    aria-label="Close"
                  >
                    <div className="chi-button__content">
                      <i className="chi-icon icon-x"></i>
                    </div>
                  </button>
                </header>
                <div className="chi-modal__content">
                  <p className="-text -m--0">Modal content</p>
                </div>
                <footer className="chi-modal__footer">
                  <button className="chi-button" data-dismiss="modal">Cancel</button>
                  <button className="chi-button -primary">Save</button>
                </footer>
              </section>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default App;
