// src/custom-elements/src/components/checkbox/checkbox.tsx
import {
  Component,
  Element,
  Event,
  EventEmitter,
  Prop,
  h,
  Watch
} from '@stencil/core';
import { CHECKBOX_CLASSES, SR_ONLY } from '../../constants/classes';
import { ChiStates } from '../../constants/states';

@Component({
  tag: 'chi-checkbox',
  scoped: true
})
export class Checkbox {
  @Element() el: HTMLElement;
  /**
   * To provide checkbox label as a string
   */
  @Prop() label: string;
  /**
   * To render the checkbox input with a respective name attribute
   */
  @Prop() name: string;
  /**
   * To render the checkbox in checked state
   */
  @Prop() checked?: boolean;
  /**
   * To add indeterminate state to checkbox
   */
  @Prop() indeterminate?: boolean;
  /**
   * To disable the checkbox
   */
  @Prop() disabled?: boolean;
  /**
   * To indicate which form field is required.
   */
  @Prop() required = false;
  /**
   * To indicate the state.
   */
  @Prop() state?: ChiStates;

  private input?: HTMLInputElement;
  id: string;

  /**
   * Triggered when the user selects or deselects the chechbox
   */
  @Event() chiChange: EventEmitter<string | boolean>;

  connectedCallback() {
    this.id = this.el.getAttribute('id');
  }

  toggle(ev: Event) {
    this.checked = (ev.target as HTMLInputElement).checked;
    this.indeterminate = false;
    this._emitChange(this.checked);
  }

  _emitChange(checked: boolean) {
    this.chiChange.emit(checked);
  }

  _updateIndeterminate() {
    this.input.indeterminate = this.indeterminate;
  }

  @Watch('indeterminate')
  updateIndeterminate(newValue: boolean, oldValue: boolean) {
    if (newValue !== oldValue) {
      this._updateIndeterminate();
    }
  }

  componentDidLoad() {
    this._updateIndeterminate();
  }

  render() {
    const requiredField = <abbr class="chi-label__required" title="Required field">*</abbr>;

    return (
      <div class={CHECKBOX_CLASSES.checkbox}>
        <input
          class={`${CHECKBOX_CLASSES.INPUT} ${this.indeterminate &&
            CHECKBOX_CLASSES.INDETERMINATE}`}
          checked={this.checked}
          disabled={this.disabled}
          id={`${this.id}-control`}
          name={this.name}
          ref={el => (this.input = el)}
          onChange={(ev: Event) => this.toggle(ev)}
          type="checkbox"
        />
        <label class={`${CHECKBOX_CLASSES.LABEL} ${this.state ? `-${this.state}` : ''}`} htmlFor={`${this.id}-control`}>
          {this.label}
          <div class={SR_ONLY}>
            Select {this.label || this.name} {this.id}
          </div>
          {this.required ? requiredField : null}
          <slot name="chi-checkbox__actions"></slot>
        </label>
      </div>
    );
  }
}

// src/chi-vue/src/components/checkbox/Checkbox.tsx
import { Component, Vue, Prop, Watch } from 'vue-property-decorator';
import { CHECKBOX_CLASSES, SR_ONLY } from '@/constants/classes';
import { GENERIC_EVENTS } from '@/constants/events';
import { CheckboxState } from '@/constants/types';

@Component({})
export default class Checkbox extends Vue {
  @Prop({ required: true }) id!: string;
  @Prop() label?: string;
  @Prop() name?: string;
  @Prop() selected?: CheckboxState;
  @Prop() disabled?: boolean;

  state = this.selected;

  @Watch('selected')
  dataState(newValue: CheckboxState, oldValue: CheckboxState) {
    if (newValue !== oldValue) {
      this.state = newValue;
    }
  }

  _emitChange(ev: Event) {
    this.$emit(GENERIC_EVENTS.CHANGE, ev);
  }

  _updateCheckboxState() {
    const checkbox = this.$refs.checkbox as HTMLInputElement;

    if (this.state === 'indeterminate') {
      checkbox.indeterminate = true;
      checkbox.classList.add(CHECKBOX_CLASSES.INDETERMINATE);
    } else {
      checkbox.indeterminate = false;
      checkbox.classList.remove(CHECKBOX_CLASSES.INDETERMINATE);
    }
  }

  mounted() {
    this._updateCheckboxState();
  }

  updated() {
    this._updateCheckboxState();
  }

  render() {
    return (
      <div class={CHECKBOX_CLASSES.checkbox}>
        <input
          v-model={this.state}
          class={`${CHECKBOX_CLASSES.INPUT} ${this.state === 'indeterminate' && CHECKBOX_CLASSES.INDETERMINATE}`}
          disabled={this.disabled}
          id={this.id}
          name={this.name}
          onChange={(ev: Event) => this._emitChange(ev)}
          ref="checkbox"
          type="checkbox"
        />
        <label class={CHECKBOX_CLASSES.LABEL} for={this.id}>
          {this.label}
          <div class={SR_ONLY}>
            Select {this.label || this.name} {this.id}
          </div>
        </label>
      </div>
    );
  }
}
